export const popularCategories = [
    'Science fiction',
    'Adventure stories',
    'Short stories',
    'Psychological fiction',
    'Romance',
    'Domestic fiction',
    'Conduct of life',
    'Historical fiction',
    'Humorous stories',
    'Horror tales',
    'Gothic fiction',
    'Fiction',
    'Detective and mystery stories',
    "Children's stories",
    'Ghost stories',
    'Autobiographical fiction',
    'Comedies',
    'Fairy Tales',
    'War Stories',
    'Poetry',
    'Ethics',
    'Other',
];
