//most common categories on Project Gutenberg
export const popularCategories = [
    'Adventure',
    'Fantasy',
    'Romance',
    'Drama',
    'History',
    'Humor',
    'Horror',
    'Gothic',
    'Fiction',
    'Science fiction',
    'Mystery',
    'Biography',
    'Fairy Tales',
    'Poetry',
    'Conduct of life',
    'Political', 
    'Philosophy',
    'Ethics',
    'Other',
];
